---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_context(load_context)
	build_blueprint(build_blueprint)
	calculate_macros(calculate_macros)
	resolve_workout_template(resolve_workout_template)
	normalize_submitted_plan(normalize_submitted_plan)
	fitness_planner(fitness_planner)
	safety_check(safety_check)
	synthesize_plan(synthesize_plan)
	write_artifacts(write_artifacts)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_context;
	build_blueprint --> calculate_macros;
	calculate_macros -.-> normalize_submitted_plan;
	calculate_macros -.-> resolve_workout_template;
	fitness_planner --> safety_check;
	load_context --> build_blueprint;
	normalize_submitted_plan --> safety_check;
	resolve_workout_template -.-> fitness_planner;
	resolve_workout_template -.-> safety_check;
	safety_check -.-> fitness_planner;
	safety_check -.-> resolve_workout_template;
	safety_check -.-> synthesize_plan;
	synthesize_plan --> write_artifacts;
	write_artifacts --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
