---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	generate_plan(generate_plan)
	reuse_execution_plan(reuse_execution_plan)
	__end__([<p>__end__</p>]):::last
	__start__ -.-> generate_plan;
	__start__ -.-> reuse_execution_plan;
	generate_plan --> __end__;
	reuse_execution_plan --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
