---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	todos_gate(todos_gate)
	research_agent(research_agent)
	write_artifacts(write_artifacts)
	blocked(blocked)
	__end__([<p>__end__</p>]):::last
	__start__ --> todos_gate;
	research_agent --> write_artifacts;
	todos_gate -.-> blocked;
	todos_gate -.-> research_agent;
	blocked --> __end__;
	write_artifacts --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
