"""Regression tests for the Alembic exclude filter.

The failure this guards against is silent and destructive: an autogenerated migration that
drops ``checkpoints`` deletes every suspended conversation, including every graph waiting on
``hitl_review``.
"""

import pytest

from src.models.table_ownership import EXCLUDE_TABLES, include_object


@pytest.mark.parametrize(
    "table",
    ["checkpoints", "checkpoint_blobs", "checkpoint_writes", "checkpoint_migrations"],
)
def test_checkpointer_tables_are_excluded(table: str) -> None:
    """Alembic must not manage the tables ``AsyncPostgresSaver.setup()`` creates."""
    assert include_object(None, table, "table", True, None) is False


@pytest.mark.parametrize("table", ["store", "store_migrations", "store_vectors"])
def test_store_tables_are_excluded(table: str) -> None:
    """Alembic must not manage the tables the long-term Postgres store creates."""
    assert include_object(None, table, "table", True, None) is False


def test_application_tables_are_included() -> None:
    """Everything Alembic does own still passes the filter."""
    assert include_object(None, "user_profile", "table", True, None) is True
    assert include_object(None, "knowledge_chunks", "table", True, None) is True


def test_only_tables_are_filtered() -> None:
    """A column that happens to share a name with an excluded table is not skipped."""
    assert include_object(None, "checkpoints", "column", True, None) is True


def test_exclude_set_covers_both_owners() -> None:
    """Both external owners contribute to the exclude set."""
    assert {"checkpoints", "store"} <= EXCLUDE_TABLES
