"""training catalogue: exercises and workout templates

Revision ID: 884ae98d4d53
Revises: 6ebdbc623a33
Create Date: 2026-08-22 15:13:45.264073
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "884ae98d4d53"
down_revision: str | None = "6ebdbc623a33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "movement_pattern",
            sa.Enum(
                "HORIZONTAL_PUSH",
                "HORIZONTAL_PULL",
                "VERTICAL_PUSH",
                "VERTICAL_PULL",
                "ANGLED_PUSH",
                "DIP",
                "HIGH_PULL",
                "SQUAT",
                "HINGE",
                "LUNGE",
                "HIP_THRUST",
                "CARRY",
                "ISOLATION",
                "HORIZONTAL_ADDUCTION",
                "ABDUCTION",
                "REAR_DELT_PULL",
                "SHOULDER_EXTENSION",
                "SCAPULAR",
                "ELBOW_FLEXION",
                "ELBOW_EXTENSION",
                "KNEE_EXTENSION",
                "KNEE_FLEXION",
                "HIP_FLEXION",
                "CALF_RAISE",
                "TRUNK_FLEXION",
                "ROTATION",
                "ANTI_ROTATION",
                "ANTI_EXTENSION",
                "ANTI_LATERAL_FLEXION",
                "FLEXION",
                "EXTENSION",
                name="movementpattern",
            ),
            nullable=False,
        ),
        sa.Column(
            "body_region",
            sa.Enum("UPPER", "LOWER", "FULL_BODY", "CORE", name="bodyregion"),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="difficultylevel"),
            nullable=False,
        ),
        sa.Column(
            "primary_muscles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "secondary_muscles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "equipment",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "contraindications",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "instructions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_body_region"), "exercise", ["body_region"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_difficulty"), "exercise", ["difficulty"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_movement_pattern"),
        "exercise",
        ["movement_pattern"],
        unique=False,
    )
    op.create_index(op.f("ix_exercise_name"), "exercise", ["name"], unique=False)
    op.create_index(
        "ix_exercise_pattern_region",
        "exercise",
        ["movement_pattern", "body_region"],
        unique=False,
    )
    op.create_table(
        "workout_template",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("days_per_week", sa.Integer(), nullable=False),
        sa.Column("popularity", sa.Integer(), nullable=False),
        sa.Column(
            "goals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "training_days",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_template_days_per_week"),
        "workout_template",
        ["days_per_week"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workout_template_days_per_week"), table_name="workout_template"
    )
    op.drop_table("workout_template")
    op.drop_index("ix_exercise_pattern_region", table_name="exercise")
    op.drop_index(op.f("ix_exercise_name"), table_name="exercise")
    op.drop_index(op.f("ix_exercise_movement_pattern"), table_name="exercise")
    op.drop_index(op.f("ix_exercise_difficulty"), table_name="exercise")
    op.drop_index(op.f("ix_exercise_body_region"), table_name="exercise")
    op.drop_table("exercise")
    # ### end Alembic commands ###
