"""Domain models from the spec: the user, the catalogue, the templates and the plan."""

from src.schemas.domain.enums import (
    ActivityLevel,
    BodyRegion,
    DifficultyLevel,
    EquipmentType,
    FaithfulnessRoute,
    FitnessGoal,
    GuardRoute,
    HitlRoute,
    InjuryStatus,
    Intent,
    MovementPattern,
    MuscleGroup,
    Node,
    ProfileRoute,
    RestrictionAction,
    Sex,
    VerificationRoute,
)
from src.schemas.domain.exercise import (
    Exercise,
    ExerciseContraindication,
    ExerciseMuscleTarget,
    MusclePriority,
)
from src.schemas.domain.plan import (
    MacroTargets,
    NutritionTargets,
    PlanDay,
    PlannedExercise,
    TrainingPlan,
)
from src.schemas.domain.profile import (
    Injury,
    MovementRestriction,
    UserEquipment,
    UserProfile,
)
from src.schemas.domain.template import (
    ExerciseSlot,
    WorkoutDayTemplate,
    WorkoutTemplate,
)
from src.schemas.domain.verification import (
    CheckName,
    Severity,
    VerificationIssue,
    VerificationResult,
)

__all__ = [
    "ActivityLevel",
    "BodyRegion",
    "CheckName",
    "DifficultyLevel",
    "EquipmentType",
    "FaithfulnessRoute",
    "Exercise",
    "ExerciseContraindication",
    "ExerciseMuscleTarget",
    "ExerciseSlot",
    "FitnessGoal",
    "GuardRoute",
    "HitlRoute",
    "Injury",
    "InjuryStatus",
    "Intent",
    "MacroTargets",
    "MovementPattern",
    "MovementRestriction",
    "MuscleGroup",
    "Node",
    "ProfileRoute",
    "MusclePriority",
    "NutritionTargets",
    "PlanDay",
    "PlannedExercise",
    "RestrictionAction",
    "Severity",
    "Sex",
    "VerificationRoute",
    "TrainingPlan",
    "UserEquipment",
    "UserProfile",
    "VerificationIssue",
    "VerificationResult",
    "WorkoutDayTemplate",
    "WorkoutTemplate",
]
