"""add exercises catalog

Creates the ``exercises`` table.

The four GIN indexes are hand-written and must stay that way: Alembic's
``--autogenerate`` does not emit an index method (``USING GIN``) for ``text[]``
columns, so a later autogenerated revision will neither create them nor notice
they are missing. They are what make the array queries in
``app/services/catalog.py`` a lookup rather than a sequential scan — the injury
and equipment filters run on every build and every repair.

Revision ID: 302477d98fd7
Revises: 8f2c41ab90d7
Create Date: 2026-08-05

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (AutoString and friends appear in generated DDL)
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "302477d98fd7"
down_revision: str | None = "8f2c41ab90d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Columns queried by set intersection or containment. Each needs GIN; a btree
# index cannot serve the `&&` and `<@` operators the catalog filters use.
_GIN_COLUMNS = ("joint_actions", "loaded_positions", "equipment", "primary_muscles")


def _array_column(name: str) -> sa.Column:
    """Build a non-null ``text[]`` column defaulting to the empty array.

    Args:
        name: Column name.

    Returns:
        The column definition.
    """
    return sa.Column(name, postgresql.ARRAY(sa.String()), nullable=False, server_default="{}")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "exercises",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("movement_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        _array_column("primary_muscles"),
        _array_column("secondary_muscles"),
        _array_column("equipment"),
        _array_column("joint_actions"),
        _array_column("loaded_positions"),
        sa.Column("contribution", sa.JSON(), nullable=False),
        sa.Column("skill_level", sa.Integer(), nullable=False),
        sa.Column("fatigue_cost", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_name"), "exercises", ["name"], unique=False)
    op.create_index(
        op.f("ix_exercises_movement_pattern"), "exercises", ["movement_pattern"], unique=False
    )

    for column in _GIN_COLUMNS:
        op.create_index(
            f"ix_exercises_{column}_gin",
            "exercises",
            [column],
            unique=False,
            postgresql_using="gin",
        )


def downgrade() -> None:
    """Downgrade schema."""
    for column in _GIN_COLUMNS:
        op.drop_index(f"ix_exercises_{column}_gin", table_name="exercises")
    op.drop_index(op.f("ix_exercises_movement_pattern"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_name"), table_name="exercises")
    op.drop_table("exercises")
