"""add user profile and plan versions

Creates ``user_profile`` (one row per user) and ``plan_versions`` (append-only
snapshots).

Autogenerated, then edited: the draft also proposed dropping the four GIN
indexes on ``exercises``. Alembic does not read the access method of an existing
index, so an index created ``USING gin`` looks like one it did not put there and
it offers to remove it. Those four drops were deleted from this file, and
``alembic/env.py`` now filters ``*_gin`` indexes so the same draft cannot be
generated again.

Revision ID: aae63dea752d
Revises: 302477d98fd7
Create Date: 2026-08-05

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (AutoString and friends appear in generated DDL)
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "aae63dea752d"
down_revision: str | None = "302477d98fd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "plan_versions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("macros", sa.JSON(), nullable=False),
        sa.Column("profile_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rubric_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("restored_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_versions_profile_hash"), "plan_versions", ["profile_hash"], unique=False
    )
    op.create_index(op.f("ix_plan_versions_user_id"), "plan_versions", ["user_id"], unique=False)

    op.create_table(
        "user_profile",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("sex", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("activity_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("days_per_week", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("equipment", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("injuries", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("preferences", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # Unique: two profile rows for one user would let concurrent turns build
    # plans against different body weights.
    op.create_index(op.f("ix_user_profile_user_id"), "user_profile", ["user_id"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_user_profile_user_id"), table_name="user_profile")
    op.drop_table("user_profile")
    op.drop_index(op.f("ix_plan_versions_user_id"), table_name="plan_versions")
    op.drop_index(op.f("ix_plan_versions_profile_hash"), table_name="plan_versions")
    op.drop_table("plan_versions")
