"""add templates and rubrics

Moves the template library and the three rubrics out of JSON files inside
``app/core/langgraph/`` and into Postgres, alongside the exercise catalog.

``rubrics`` has a composite primary key ``(name, version)`` on purpose. Seeding a
new rubric version inserts a row rather than updating one, so a version that a
stored verify report cites is never rewritten and that verdict stays
reproducible. ``is_active`` selects the version the application reads.

The two GIN indexes on ``templates`` are hand-written for the same reason as the
ones on ``exercises``: Alembic's ``--autogenerate`` does not emit ``USING GIN``
for array columns, so a later autogenerated revision would neither create them
nor notice they are gone. ``query_templates`` filters by membership in ``goal``
and ``level``, which btree cannot serve.

Revision ID: c4a91f7b2d30
Revises: 39b53dfc1573
Create Date: 2026-08-07

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (AutoString and friends appear in generated DDL)
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c4a91f7b2d30"
down_revision: str | None = "39b53dfc1573"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "templates",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("days_per_week", sa.Integer(), nullable=False),
        sa.Column("goal", postgresql.ARRAY(sa.String()), nullable=False, server_default="{}"),
        sa.Column("level", postgresql.ARRAY(sa.Integer()), nullable=False, server_default="{}"),
        sa.Column("popularity", sa.Integer(), nullable=False),
        sa.Column("days", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_templates_days_per_week"), "templates", ["days_per_week"], unique=False
    )
    for column in ("goal", "level"):
        op.create_index(
            f"ix_templates_{column}_gin",
            "templates",
            [column],
            unique=False,
            postgresql_using="gin",
        )

    op.create_table(
        "rubrics",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name", "version"),
    )
    op.create_index(op.f("ix_rubrics_is_active"), "rubrics", ["is_active"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_rubrics_is_active"), table_name="rubrics")
    op.drop_table("rubrics")

    for column in ("goal", "level"):
        op.drop_index(f"ix_templates_{column}_gin", table_name="templates")
    op.drop_index(op.f("ix_templates_days_per_week"), table_name="templates")
    op.drop_table("templates")
